// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC2Kcyp9cwWkQNXFUnUo2UdzDdrkiMwNk',
    appId: '1:521724918730:web:a761040c79b3397f272d33',
    messagingSenderId: '521724918730',
    projectId: 'aiquaboost-b097c',
    authDomain: 'aiquaboost-b097c.firebaseapp.com',
    storageBucket: 'aiquaboost-b097c.appspot.com',
    measurementId: 'G-MG4V74ETCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOjsd3K3f9RZHO17m1UoXnIHd8PVg-5Vc',
    appId: '1:521724918730:android:14d3b6799e3621f2272d33',
    messagingSenderId: '521724918730',
    projectId: 'aiquaboost-b097c',
    storageBucket: 'aiquaboost-b097c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYoLqWM1TbaualdpnFHHpla6opDunbmXY',
    appId: '1:521724918730:ios:44eff06aebaa3c5b272d33',
    messagingSenderId: '521724918730',
    projectId: 'aiquaboost-b097c',
    storageBucket: 'aiquaboost-b097c.appspot.com',
    iosBundleId: 'com.example.aiquaboost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYoLqWM1TbaualdpnFHHpla6opDunbmXY',
    appId: '1:521724918730:ios:44eff06aebaa3c5b272d33',
    messagingSenderId: '521724918730',
    projectId: 'aiquaboost-b097c',
    storageBucket: 'aiquaboost-b097c.appspot.com',
    iosBundleId: 'com.example.aiquaboost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC2Kcyp9cwWkQNXFUnUo2UdzDdrkiMwNk',
    appId: '1:521724918730:web:4c33c8cd1462a327272d33',
    messagingSenderId: '521724918730',
    projectId: 'aiquaboost-b097c',
    authDomain: 'aiquaboost-b097c.firebaseapp.com',
    storageBucket: 'aiquaboost-b097c.appspot.com',
    measurementId: 'G-W9L3ZXJ2RK',
  );
}
